# Generated by Django 4.2.7 on 2026-02-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='metrics',
            field=models.JSONField(default=dict, help_text='Detailed scoring metrics'),
        ),
    ]
