# Generated by Django 4.2.7 on 2026-03-18 10:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resumeanalysis_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='last_auto_saved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='ats_score',
            field=models.FloatField(default=0.0, help_text='ATS compatibility score'),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='ats_suggestions',
            field=models.JSONField(default=list, help_text='ATS-specific improvement tips'),
        ),
        migrations.CreateModel(
            name='ResumeShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='resumes.resume')),
            ],
            options={
                'db_table': 'resumes_resumesharelink',
            },
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='resume_versions/')),
                ('extracted_text', models.TextField(blank=True)),
                ('ai_score', models.FloatField(default=0.0)),
                ('ai_feedback', models.JSONField(default=dict)),
                ('skills_identified', models.JSONField(default=list)),
                ('change_note', models.TextField(blank=True, help_text='What changed in this version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='resumes.resume')),
            ],
            options={
                'db_table': 'resumes_resumeversion',
                'ordering': ['-version_number'],
                'unique_together': {('resume', 'version_number')},
            },
        ),
    ]
