# Generated by Django 4.2.7 on 2026-03-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_google_id_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='has_company_proof',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='past_hires',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
