# Generated by Django 4.2.7 on 2026-04-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_recruiterprofile_has_company_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='is_linkedin_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='is_website_verified',
            field=models.BooleanField(default=False),
        ),
    ]
