# Generated by Django 4.2.7 on 2026-02-02 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField()),
                ('skill_match_percentage', models.FloatField()),
                ('experience_match_percentage', models.FloatField()),
                ('location_match', models.BooleanField()),
                ('salary_expectation_match', models.BooleanField()),
                ('reasons', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_matches', to='jobs.job')),
            ],
            options={
                'db_table': 'matches_jobmatch',
                'ordering': ['-match_score'],
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
