# Generated by Django 4.2.7 on 2026-03-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_applicationstatushistory_interviewschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='about_role',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='nice_to_have',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
